mutation($createArticleInput: CreateArticleInput!) {
  createArticle(createArticleInput: $createArticleInput) {
    id
    slug
    title
    excerpt
    content
    createDate
    updateDate
    status
  }
}