mutation($createCategoryInput: CreateCategoryInput!) {
    createCategory(createCategoryInput: $createCategoryInput) {
        id
        slug
        title
        createDate
        updateDate
    }
}